import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import { Toaster } from 'sonner'

const poppins = Poppins({
  variable: '--font-primary',
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: {
    template: '%s | Kadoo Academy',
    default: 'Kadoo Academy',
  },
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={`${poppins.variable}`} suppressHydrationWarning={true}>
        {children}
        <Toaster richColors position="top-right" />
      </body>
    </html>
  )
}
